services:
  - type: web
    name: financeiro-api
    runtime: docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.wihcapqflxrpglxkqxzb.supabase.co:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: R0dr1g0#@24041998